### PR TITLE
Revert "Add OpenTimestamps writeup to drafts"

### PR DESCRIPTION
**Pull request by kiarafbickers**
Reverts WebOfTrustInfo/ID2020DesignWorkshop#23

### CODE REVIEW

**Comment by petertodd** [comment]
Lol, that was fast. :)

**Comment by kiarafbickers** [comment]
You want to add this to the [Fall directory](https://github.com/WebOfTrustInfo/rebooting-the-web-of-trust-fall2016) instead.

**Comment by petertodd** [comment]
Ah, I see! Hmm, doesn't look like there's a similar "drafts" thing there; how about I just add a copy of the blog post to draft-documents?

**Comment by kiarafbickers** [comment]
The [advanced reading](https://github.com/WebOfTrustInfo/rebooting-the-web-of-trust-fall2016/tree/master/topics-and-advance-readings) spot is what you want. Drafts is for the white papers we'll put together at the event.

**Comment by kiarafbickers** [comment]
@petertodd Oh and you don't have to submit a pull request. You can just add it in. 👍

**Comment by petertodd** [comment]
Done! https://github.com/WebOfTrustInfo/rebooting-the-web-of-trust-fall2016/blob/1bc5b56b72f95a4d1665f148aa1deba581fc580d/topics-and-advance-readings/opentimestamps.md

**Pull request closed without merging**
